### ISSUE TITLE
Hansard results sorting - can these be chronological?

### ISSUE THREAD

**Issue by paullenz** [mysociety/pombola#287] opened 2012-02-07 06:52 UTC
Currently I am not sure what the criterion for the sorting of Hansard search results is - suspect it could be relevance?  Could it be made to be chronological, with most recent first please?

**Comment by duncanparkes** [comment] 2016-03-09 15:10
There is currently a choice of three different orderings for search results from Hansard, with 'relevance' as the default.

Should 'newest first' be the default?

![2016-03-09-150108_1366x768_scrot](https://cloud.githubusercontent.com/assets/56265/13639533/172a6f5a-e609-11e5-89c3-6adb985126e6.png)

**Comment by tmtmtmtm** [comment] 2016-03-09 15:22
This was fixed in https://github.com/mysociety/pombola/pull/1625 (closing https://github.com/mysociety/pombola/issues/1607 which was a duplicate of this)

**Closed by tmtmtmtm** 2016-03-09 15:22 UTC
Labels: code, Difficulty 2, enhancement, KE
