### ISSUE TITLE
Can't deploy ZA site due to old setuptools

### ISSUE THREAD

**Issue by Flupsy** [mysociety/pombola#1674] opened 2015-06-22 08:10 UTC
Deploying the ZA site on dassie fails to build the wheel files (`error: invalid command 'bdist_wheel'`).  @mhl had a look and thinks it's something to do with the wrong version of setuptools being used.

This is semi-urgent: bokkie is going away in a couple of weeks, and I've rescheduled the move to dassie for Monday 29th June.

**Comment by mhl** [comment] 2015-06-22 08:55
To reproduce in that virtualenv, you can try uninstalling and reinstalling `mock`, say:

```
mark@dassie:~/pombola$ . ../pombola-virtualenv/bin/activate
(pombola-virtualenv)mark@dassie:~/pombola$ pip uninstall mock
Uninstalling mock-1.0.1:
  /home/mark/pombola-virtualenv/lib/python2.7/site-packages/mock-1.0.1-py2.7.egg-info
  /home/mark/pombola-virtualenv/lib/python2.7/site-packages/mock.py
  /home/mark/pombola-virtualenv/lib/python2.7/site-packages/mock.pyc
Proceed (y/n)? y
  Successfully uninstalled mock-1.0.1
(pombola-virtualenv)mark@dassie:~/pombola$ pip install mock
Collecting mock
  Using cached mock-1.0.1.tar.gz
/home/mark/pombola-virtualenv/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/setuptools/command/install_scripts.py:3: UserWarning: Module pip was already imported from /home/mark/pombola-virtualenv/local/lib/python2.7/site-packages/pip/__init__.pyc, but /usr/lib/python2.7/dist-packages is being added to sys.path
  from pkg_resources import Distribution, PathMetadata, ensure_directory
Building wheels for collected packages: mock
  Running setup.py bdist_wheel for mock
  Complete output from command /home/mark/pombola-virtualenv/bin/python -c "import setuptools;__file__='/tmp/pip-build-_ESAGA/mock/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpGnTGogpip-wheel-:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for mock
Failed to build mock
Installing collected packages: mock
  Running setup.py install for mock
Successfully installed mock-1.0.1
```

I think the errors with trying to build the wheel files are innocuous, in that the packages still seem to be usable, but it would be best to completely understand this. I think the error is due to:

> The wheel project provides a bdist_wheel command for setuptools (requires setuptools >= 0.8.0).

... from: https://wheel.readthedocs.org/en/latest/

... whereas on dassie, doing:

```
git clone https://github.com/mysociety/pombola.git
cd pombola
bin/prepare_environment
[... includes the `invalid command 'bdist_wheel'` errors for many packages ...]
. ../pombola-virtualenv/bin/activate
```

Gives you a python with a setuptools that's too old:

```
(pombola-virtualenv)mark@dassie:~/pombola$ python
Python 2.7.3 (default, Mar 13 2014, 11:03:55) 
[GCC 4.7.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import setuptools
>>> setuptools.__version__
'0.6'
```

However, on existing virtualenvs for Pombola sites on dassie, we have a much later setuptools:

```
(pombola-virtualenv)mzalendo-south-africa@bokkie:/var/www/www.pa.org.za/pombola$ python
Python 2.7.3 (default, Jan  2 2013, 13:56:14) 
[GCC 4.7.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import setuptools
>>> setuptools.__version__
'17.1.1'
```

I'm confused about this because `bin/prepare_environment` makes a point of installing an up-to-date pip:

https://github.com/mysociety/pombola/blob/master/bin/prepare_environment.bash#L41-L45

... which succeeds (pip is the same in bokkie and dassie virtualenvs). The script from commonlib that does that also says it will upgrade setuptools:

https://github.com/mysociety/commonlib/blob/master/bin/get_pip.bash

... but apparently that doesn't work:

```
(pombola-virtualenv)mark@dassie:~/pombola$ pip install setuptools --no-use-wheel --upgrade
/home/mark/pombola-virtualenv/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Requirement already up-to-date: setuptools in /home/mark/pombola-virtualenv/lib/python2.7/site-packages
```

That warning, described [here](https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning) can be fixed with:

```
sudo apt-get install libffi-dev
pip install --no-use-wheel pyopenssl ndg-httpsclient pyasn1
```

However, after that it still won't upgrade setuptools:

```
(pombola-virtualenv)mark@dassie:~/pombola$ pip install setuptools --no-use-wheel --upgrade
Requirement already up-to-date: setuptools in /home/mark/pombola-virtualenv/lib/python2.7/site-packages
(pombola-virtualenv)mark@dassie:~/pombola$ python -c 'import setuptools; print setuptools.__version__'0.6
```

I was a bit confused about why this is different on the two machines, but noticed that the version of pip installed by `get-pip.py` has changed recently:

https://github.com/pypa/pip/commits/develop/contrib/get-pip.py


And the pip changelog includes, in version 7.0.0 (2015-05-21):

> Removed the temporary modifications (that began in pip v1.4 when distribute and setuptools merged) that allowed distribute to be considered a conflict to setuptools. pip install -U setuptools will no longer upgrade "distribute" to "setuptools". Instead, use pip install -U distribute (PR #2767).

Indeed, after `pip install --distribute`, we get an up-to-date setuptools and the error is gone:

```
(pombola-virtualenv)mark@dassie:~/pombola$ python -c 'import setuptools; print setuptools.__version__'
17.1.1
(pombola-virtualenv)mark@dassie:~/pombola$ pip uninstall mock
Uninstalling mock-1.0.1:
  /home/mark/pombola-virtualenv/lib/python2.7/site-packages/mock-1.0.1-py2.7.egg-info
  /home/mark/pombola-virtualenv/lib/python2.7/site-packages/mock.py
  /home/mark/pombola-virtualenv/lib/python2.7/site-packages/mock.pyc
Proceed (y/n)? y
  Successfully uninstalled mock-1.0.1
(pombola-virtualenv)mark@dassie:~/pombola$ pip install mock
Collecting mock
  Using cached mock-1.0.1.tar.gz
Building wheels for collected packages: mock
  Running setup.py bdist_wheel for mock
  Stored in directory: /home/mark/.cache/pip/wheels/c9/b4/72/4de2802cbc4bfd82f938ff92015e1b42f01131583675ab4d00
Successfully built mock
Installing collected packages: mock
Successfully installed mock-1.0.1
```

So I think the fix is to update commonlib's https://github.com/mysociety/commonlib/blob/master/bin/get_pip.bash#L24 line to upgrade distribute instead of setuptools. (Or perhaps it would be better to have belt and braces and just insert the `pip install --upgrade distribute` before that line.)

**Comment by duncanparkes** [comment] 2015-09-07 08:20
Is this fixed? I'm sure I deployed www.pa.org.za on dassie this week.

**Comment by mhl** [comment] 2015-09-08 13:12
Yes, it's fixed - if you follow the link at the end of the bug report, you'll see the change is there.

**Closed by mhl** 2015-09-08 13:12 UTC
Labels: 1 - Contender, Difficulty 1
